config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  resources :users do
    resources :diets, only: [:new, :create, :show]
    resources :user_stats, only: [:new, :create, :edit, :update]
  end
  resources :diets, only: [:edit, :update]
  

  resources :meals do
    resources :foods, only: [:new, :create, :index]
  end
  resources :foods

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authenticate_user!
def index
    if user_signed_in?
    @user = current_user
    @diet = Diet.find_by(user_id: @user.id)
    end
end

end

app/views/home/index.erb
<div class="d-flex align-items-center flex-column">
  <div class="card text-white bg-primary mb-3" style="max-width: 40rem;">
      
    <div class="card-header text-center">
      <% if @user %>
        Hi <%= @user.name %>!
      <% else %>
        <p> Hello!</p>
      <% end %>
    </div>
    <div class="card-body">
      <h4 class="card-title align-text-center text-center">
        <% if @user && @diet == nil %>
        Let's Begin
        <% else %>
        <%= link_to 'Sign up', new_user_registration_path, class: "nav-link text-white" %>
        <%= link_to 'Sign in', new_user_session_path, class: "nav-link text-white" %>
        <% end %>
      </h4>
      <p class="card-text align-text-center text-center">
      <%if @user && @diet == nil%>
        On the next few screens, we are going to ask some basic information about you. Answer the questions as accurately as possible to help us create an effective diet for you. If you make a mistake, don't worry. Keep going and you can easily edit it later.<br>
        <br>
        <button type="button" class="btn btn-secondary"><%= link_to 'Create Diet', new_user_user_stat_path(current_user), class: "text-decoration-none" %></button>
        <% else %>
        Welcome to your new diet coach!
        <% end %>
      </p>        
    </div>
  </div>
</div>