config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  resources :users do
    resources :diets, only: [:new, :create, :show]
    resources :user_stats, only: [:new, :create, :edit, :update]
  end
  resources :diets, only: [:edit, :update]
  

  resources :meals do
    resources :foods, only: [:new, :create, :index]
  end
  resources :foods

  root to: "home#index"
end

app/models/meal.rb
class Meal < ApplicationRecord
    has_many :foods, dependent: :destroy
    has_many :users, through: :foods
    
    scope :high_protein, -> { where("protein > 30")}
    scope :high_carb, -> { where("carbs > 30")}
    scope :high_fat, -> { where("fat > 15")}

    def foods_attributes=(food_attributes)
        food_attributes.values.each do |food|
            if food[:name] != "" && food[:serving_size] != "" && food[:carbs] != "" && food[:fat] != "" && food[:protein] != "" && food[:user_id] != ""
                self.foods.build(food)
            end
        end
    end

    def get_user_meal_foods(user)
        self.foods.where(user_id: user.id)
    end

end
    

app/controllers/meals_controller.rb
class MealsController < ApplicationController
    before_action :set_meal, only: [:show, :edit, :update, :destroy]
    def index
        if params[:filter == ""]
            @meals = Meal.all
        elsif params[:filter] == "High Protein"
            @meals = Meal.high_protein
        elsif params[:filter] == "High Carb"
            @meals = Meal.high_carb
        else params[:filter] == "High Fat"
            @meals = Meal.high_fat
        end

        @user_meals = @user.meals.uniq
        @community_meals = @meals - @user.meals
    end
    
    def new
        @meal = Meal.new
        5.times { @meal.foods.build }
    end

    def create
       assign_meal_macros
       @user = current_user
       @diet = Diet.find_by(user_id: @user.id)
       @meal = Meal.new(meal_params)
            if @meal.save

                 if params[:meal][:location]
                     redirect_to user_diet_path(@user, @diet)
                 else
                 redirect_to meal_path(@meal) 
                 end
            else
            render "new"
            end
    end

    def show
    
    end

    def edit
       
    end

    def update
        @meal.update(name: params[:meal][:name])
        @counter = 0
        @meal.foods.each do |food| 
          food.update(meal_params[:foods_attributes].values[@counter])
          @counter += 1
        end
        if @meal.errors.any?
          render "edit"
        else
          redirect_to meal_path(@meal)
        end
    end

    def destroy
        @user.meals.delete(@meal)
        @user_foods = Food.associated_food(@user.id, @meal.id)
        if @meal.foods.count == 0
          @meal.delete
        end
       redirect_to meals_path
    end

    private

    def meal_params
        params.require(:meal).permit(:name, :carbs, :fat, :protein, foods_attributes: [:name, :serving_size, :carbs, :fat, :protein, :user_id])
    end

    def set_meal
        @meal = Meal.find_by(id: params[:id])
    end
    
    def assign_meal_macros
        total_meal_carb_count
        total_meal_fat_count
        total_meal_protein_count
    end


    def total_meal_carb_count
        carb_count
        @total_carbs = @carbcount.reduce(:+)
        params[:meal][:carbs] = @total_carbs
    end

    def carb_count
        @carbcount = meal_params[:foods_attributes].values.map do |food|
        food[:carbs].to_i
        end
    end

    def total_meal_protein_count
        protein_count
        @total_protein = @proteincount.reduce(:+)
        params[:meal][:protein] = @total_protein
    end

    def protein_count
        @proteincount = meal_params[:foods_attributes].values.map do |food|
        food[:protein].to_i
        end
    end

    def total_meal_fat_count
        fat_count
        @total_fat = @fatcount.reduce(:+)
        params[:meal][:fat] = @total_fat
    end

    def fat_count
        @fatcount = meal_params[:foods_attributes].values.map do |food|
        food[:fat].to_i
        end
    end

end

app/helpers/meals_helper.rb
module MealsHelper

    
end

app/views/meals/_new.erb
    <%= f.text_field :name, label: "Meal Name"%>
    <%= f.hidden_field :carbs %>
    <%= f.hidden_field :protein %>
    <%= f.hidden_field :fat %>
    <h6 class="text-center text-white"> Add your foods below </h6>
    <%= f.fields_for :foods do | i | %>
        <%= i.text_field :name, label: "Food Name" %> 
        <%= i.number_field :serving_size, label: "Serving Size", append: "grams" %>
        <%= i.number_field :carbs, label: "Carbs", append: "grams" %>
        <%= i.number_field :fat, label: "Fat", append: "grams" %>
        <%= i.number_field :protein, label: "Protein", append: "grams" %>
        <%= i.hidden_field :user_id, value: this_user.id %>
        <br>
    <% end %> 
    <%= f.submit %>

app/views/meals/edit.erb
<div class="container">
  <div class="d-flex align-items-center flex-column">
    <div class="card text-white bg-primary mb-3" style="max-width: 400rem;">
      <div class="card-header text-center">
        Edit Meal
      </div>
      <div class="card-body">
        <%= bootstrap_form_with model: @meal, local: true, layout: :horizontal, label_col: "col-3", control_col: "col-9" do |f| %>
        <%= render partial: "meals/new", locals: {this_user: @user, f: f} %>
        <% end %>
      <br>
      </div>
    </div>
  </div>
</div>

app/views/meals/index.erb
<div class="container">
  <div class="row justify-content-center">   
    <div class="col-4 d-flex justify-content-center">
      <ul class="list-group list-unstyled w-75">
        <h5 class="text-secondary">Your Meals</h5>
        <% @user_meals.each do |meal| %>
        <li><%= link_to "#{meal.name}", meal_path(meal), class: "list-group-item list-group-item-action font-weight-bolder list-group-item-dark" %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-4 d-flex justify-content-center">
      <ul class="list-group list-unstyled w-75">
        <h5 class="text-secondary">Community Meals</h5>
        <% @community_meals.each do |meal| %>
        <li><%= link_to "#{meal.name}", foods_path(:meal_id => meal.id), method: "post", class: "list-group-item list-group-item-action font-weight-bolder list-group-item-dark", local: true %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-4 d-flex justify-content-center">
      <%= bootstrap_form_with(url: meals_path, method: "get", local: true) do %>
      <%= label_tag :filter %>
      <%= select_tag :filter, options_for_select(["High Protein", "High Carb", "High Fat"]), prompt: "Select Macro" %>
      <%= submit_tag("Filter") %>
      <% end %>
    <br>
    </div>
  </div>
</div>

app/views/meals/new.erb
<div class="container">
  <div class="d-flex align-items-center flex-column">
    <div class="card text-white bg-primary mb-3" style="max-width: 400rem;">
      <div class="card-header text-center">
        Edit Meal
      </div>
      <div class="card-body">
      <%= bootstrap_form_with model: @meal, local: true, layout: :horizontal, label_col: "col-3", control_col: "col-9" do |f| %>
      <%= render partial: "meals/new", locals: {this_user: @user, f: f} %>

  <% end %>
  <br>
      </div>
    </div>
  </div>
</div>

app/views/meals/show.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col">
      <h3 class="text-center"> <%=@meal.name%> </h3>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-9">
      <table class="table table-bordered table-striped"> 
        <thead>
          <tr>
            <th class="w-25 text-center" scope="col">Food</th>
            <th class="w-25 text-center" scope="col">Serving Size</th>
            <th class="w-25 text-center" scope="col">Carbs</th>
            <th class="w-25 text-center" scope="col">Fat</th>
            <th class="w-25 text-center" scope="col">Protein</th>
          </tr>
        </thead>
        <% @meal.get_user_meal_foods(@user).each do | food | %>
        <tbody>
          <tr>
            <th class="w-20" scope="row"><%=food.name%></th>
            <td><%=food.serving_size%> grams</td>
            <td><%=food.carbs%> grams</td>
            <td><%=food.fat%> grams</td>
            <td><%=food.protein%> grams</td>
          </tr>  
        </tbody>
        <% end %>
      </table>    
    </div>
    <div class="col-9 d-flex justify-content-center">
      <button type="button" class="btn btn-primary"><%= link_to "Edit meal", edit_meal_path(@meal), class: "text-white" %></button>
      <button type="button" class="btn btn-primary"><%= link_to("Delete your meal", meal_path(@meal), method: :delete, class: "text-white", data:{confirm: "Do you really want to delete me?"}) %></button>
    </div>  
  </div>
</div>