config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  resources :users do
    resources :diets, only: [:new, :create, :show]
    resources :user_stats, only: [:new, :create, :edit, :update]
  end
  resources :diets, only: [:edit, :update]
  

  resources :meals do
    resources :foods, only: [:new, :create, :index]
  end
  resources :foods

  root to: "home#index"
end

app/models/diet.rb
class Diet < ApplicationRecord
    belongs_to :user
    validates :goal, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
    validates :current_weight, presence: true, numericality: true
    validates :target_weight, presence: true, numericality: true
    validates :activity_level, presence: true
    

    def daily_calorie_variance
        (calculate_weight_change * 3500).floor / Integer(self.end_date - self.start_date)
    end
        
    def calculate_weight_change
        if self.goal == "lose"
          self.current_weight - self.target_weight
        elsif self.goal == "build"
          self.target_weight - self.current_weight
        else 
          0
        end
    end    
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
    helper_method :daily_calories

def new
    @diet = Diet.new(user_id: params[:user_id])
end

def create
    @diet = Diet.new(diet_params)
    if @diet.save
       redirect_to user_diet_path(@user, @diet)
    else  
        render "/diets/new"
    end
end 

def show
    
    @diet = @user.diet
    @daily_calories = (@user.total_energy_expenditure - @diet.daily_calorie_variance)
    @total_cpm = @user.total_energy_expenditure * 0.25
    @start_date = @user.diet.start_date
    @end_date = @user.diet.end_date
    @food = Food.find_by(name: params[:name])
    @meals = @user.meals.uniq
    @meal = Meal.new
    if !params[:meal_id].blank?
    @selected_meal = Meal.find_by_id(params[:meal_id])
    end
    6.times { @meal.foods.build }
    
end

def edit 
    @diet = Diet.find_by(user_id: @user.id)
end

def update
    @diet = Diet.find_by(user_id: @user.id)
      @diet.update(diet_params)
      if @diet.errors.any?
        render "edit"
      else
        redirect_to user_diet_path(@user, @diet)
      end
  end



private

def diet_params
   params.require(:diet).permit(:goal, :current_weight, :target_weight, :activity_level, :meals_per_day, :end_date, :start_date, :user_id)
end

def daily_calories
    @diet = @user.diet
    (@user.total_energy_expenditure - @diet.daily_calorie_variance)
end

end

app/helpers/diets_helper.rb
module DietsHelper 
    
    def calories_per_meal
        (daily_calories / current_user.diet.meals_per_day)
    end

    def protein_amount
        ((calories_per_meal * 0.30) / 4).floor
    end

    def fat_amount
        ((calories_per_meal * 0.30) / 9).floor
    end

    def carbs_amount
        ((calories_per_meal * 0.40) / 4).floor
    end

end

app/views/diets/_form.erb
<div class="card text-white bg-primary mb-3" style="width: 30rem;">
  <div class="card-header">Diet Info</div>
  <div class="card-body">
    <h4 class="card-title">Answer as accurately as possible</h4>
    <p class="card-text">
    <h5 class="text-white">What is your goal?</h5>
    <%= f.radio_button :goal, "lose", label: "I want to lose bodyfat(CURRENT WEIGHT must be MORE than TARGET WEIGHT)." %>
    <%= f.radio_button :goal, "maintain", label: "I want to maintain." %>
    <%= f.radio_button :goal, "build", label: "I want to build muscle(CURRENT WEIGHT must be LESS than TARGET WEIGHT)." %>
  <br>
    <%= f.number_field :current_weight, label: "Current weight in pounds.", append: "lbs" %> <br>
    <%= f.number_field :target_weight, label: "Target weight in pounds.", append: "lbs" %> <br>
    <h5 class="text-white">What is your average daily activity level?</h5>
    <%= f.radio_button :activity_level, 1, label: "Sedentary(desk worker with little to no exercise)" %>
    <%= f.radio_button :activity_level, 2, label: "Lightly active(sales person/light exercise 1-3 days/week)" %>
    <%= f.radio_button :activity_level, 3, label: "Moderately active(teacher/moderate exercise 3-5 days/week)" %>
    <%= f.radio_button :activity_level, 4, label: "Very active(nurse/moderate exercise 5-7 days/week)" %>
    <%= f.radio_button :activity_level, 5, label: "Extremely active(construction worker/very hard exercise)" %>
  <br>
    <h5 class="text-white"> How many meals per day do you want to eat? </h5>
    <%= f.radio_button :meals_per_day, 1, label: "1 meal per day" %>
    <%= f.radio_button :meals_per_day, 2, label: "2 meals per day" %>
    <%= f.radio_button :meals_per_day, 3, label: "3 meals per day" %>
    <%= f.radio_button :meals_per_day, 4, label: "4 meals per day" %>
    <%= f.radio_button :meals_per_day, 5, label: "5 meals per day" %>
    <%= f.radio_button :meals_per_day, 6,  label: "6 meals per day" %>
    <br>
    <%= f.date_field :start_date, label: "Select your start date" %>

    <%= f.date_field :end_date, label: "Select your end date" %> 
    <%= f.hidden_field :user_id %>
    <%= f.submit "Submit" %>
    </p>
  </div>
</div>

app/views/diets/edit.erb
<div class="container">
  <% if @diet.errors.any? %>
  <div class="alert alert-dismissible alert-warning">
    <h4 class="alert-heading">Uh-oh</h4>
    <p class="mb-0"><%= @diet.errors.full_messages.to_sentence %></p>
  </div>
  <% end %>
  <div class="d-flex align-items-center flex-column">
    <h1>Edit Diet</h1>
  <br>
    <%= bootstrap_form_with model: @diet, local: true do |f| %>
    <%= render 'form', f: f %>
  <% end %>
  </div>
</div>

app/views/diets/new.erb
<div class="container">
  <% if @diet.errors.any? %>
  <div class="alert alert-dismissible alert-warning">
    <h4 class="alert-heading">Warning!</h4>
    <p class="error"><%= @diet.errors.full_messages.to_sentence %></p>
  </div>
  <% end %>
  <div class="d-flex align-items-center flex-column">
    <%= bootstrap_form_with model: [@user, @diet], method: 'post', local: true do |f| %>
    <%= render 'form', f: f %>
  <% end %>
</div>

app/views/diets/show.erb
<div class="container">
  <div class="row justify-content-center">   
    <div class="col d-flex justify-content-center">
      <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
        <div class="card-body">
          <%= bootstrap_form_with model: @diet, url: diet_path(@diet), method: "patch", local: true do |f| %>
          <%= f.number_field :current_weight, label: "update current weight", append: "lbs" %>
          <%= f.submit "Submit" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col d-flex justify-content-center">
      <% if Date.today < @start_date %>
        <p> Your diet starts in <%= Integer(@start_date - Date.today) %>day('s). This is just a preview of day 1.</p> 
        <p class="font-weight-bold"> <%= link_to 'Click here to edit the diet and change it\'s start date', edit_diet_path(@diet), data:{confirm: "Editing diet will change current parameters. Are you sure you want to edit?"} %></p>
      <% elsif Date.today > @end_date %>
        <p> Your diet is over! Congrats! </p>
      <% else %>
        <h4>Today's date: <%= Date.today.strftime("%a, %e %b %Y") %></h4>
      <% end %>
    </div>
  </div>
    <br>
  <div class="row d-flex justify-content-center">
    <h4>Try to hit the following targets for each of your <%=@diet.meals_per_day%> meals. </h4>
  </div>
    <br>
  <div class="row d-flex justify-content-center">
    <div class="col d-flex justify-content-center">
      <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
        <div class="card-body">
          <h4 class="card-title">Carbs: <%= carbs_amount %>g </h4>
        </div>
      </div>
    </div>
    <div class="col d-flex justify-content-center">
      <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
        <div class="card-body">
          <h4 class="card-title">Protein: <%= protein_amount %>g </h4>
        </div>
      </div>
    </div>
    <div class="col d-flex justify-content-center">
      <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
        <div class="card-body">
          <h4 class="card-title">Fat: <%= fat_amount %>g </h4>
        </div>
      </div>
    </div>
    <div class="col d-flex justify-content-center">
      <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
        <div class="card-body">
          <h4 class="card-title">Total calories: <%= calories_per_meal %> </h4>
        </div>
      </div>
    </div>
  </div>
<br>
<br>
<div class="row d-flex justify-content-center"> 
  <div class="col-4 d-flex align-items-start">
    <div class="card text-white bg-dark mb-3" style="width: 30rem;">
      <div class="card-header text-center">
        Select a meal
      </div>
      <div class="card-body">
 <%= bootstrap_form_with(url: user_diet_path(@user, @diet), method: "get", local: true) do |f| %>
    <%= f.select :meal_id, options_from_collection_for_select(@meals, :id, :name), include_blank: true %><br>
    <%= f.submit "Select Meal" %>
    <% end %>
      </div>
    </div>
  </div>
  <div class="col-4 d-flex align-items-start">
    <div class="card text-white bg-dark mb-3" style="width: 30rem;">
      <div class="card-header text-center">
        Create a meal
      </div>
      <div class="card-body">
       <%= bootstrap_form_with(model: @meal, url: "/meals", method: "post", layout: :horizontal, label_col: "col-4", control_col: "col-8") do |f| %>
       <%= f.hidden_field :location, value: "diets" %>
       <%= render partial: "meals/new", locals: {this_user: @user, f: f} %>
       <% end %>
       </div>
      </div>
    </div>

<div class=" col-4 d-flex align-items-start">
    <div class="card text-white bg-dark mb-3" style="width: 30rem;">
      <div class="card-header text-center">
        Meal
      </div>
      <div class="card-body">
   <% if @selected_meal %>
    <p><%= @selected_meal.name %> meal stats:<br>
    carbs: <%= @selected_meal.carbs %> protein: <%= @selected_meal.protein %> fat: <%= @selected_meal.fat %>  calories: <%= total_calories(@selected_meal) %>
    <p>Food stats:<br>
    <% @selected_meal.foods.where(user_id: @user.id).each do |food| %> 
    <%= food.name %> - carbs: <%= food.carbs %> protein: <%= food.protein %> fat: <%= food.fat %> calories: <%= total_calories(food)%><br>
        <%end%></p>
    <% end %>
    </div>
    </div>
    </div>
    </div>
</div>