config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }

  resources :users do
    resources :diets, only: [:new, :create, :show]
    resources :user_stats, only: [:new, :create, :edit, :update]
  end
  resources :diets, only: [:edit, :update]
  

  resources :meals do
    resources :foods, only: [:new, :create, :index]
  end
  resources :foods

  root to: "home#index"
end

app/views/layouts/_nav.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div><%= link_to image_tag 'CP_Logo_Cropped.png', class: "navbar-brand img-fluid", style: "height: 4rem"%></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <% if current_user.diet != nil %>
      <li class="nav-item">
      <%= link_to 'Home', user_diet_path(current_user, current_user.diet), class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'New Diet', edit_diet_path(current_user.diet), data:{confirm: "Changing any diet parameters is permanent. Are you sure you want to change your diet?"}, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
      <%= link_to 'Edit your account', edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign out', destroy_user_session_path, method: "delete", class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'New Meal', new_meal_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'My Meals', meals_path, class: "nav-link" %>
      </li>

      <% else %>
      <li class="nav-item">
      <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
      </li>

      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DietCoach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <%= render 'layouts/nav'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>